### ISSUE TITLE
Numerous spelling and grammar errors

### ISSUE THREAD

**Issue by BuckWoody** [Azure/MachineLearningSamples-TDSPUCIAdultIncome#14]
There are several grammar and spelling errors on this page: https://github.com/Azure/MachineLearningSamples-TDSPUCIAdultIncome/blob/master/docs/how-to-use-tdsp-in-azure-ml.md - any way we can help clean those up?

**Comment by bradsev** [comment]
I’ll clean it up Buck. -Brad

**Comment by deguhath** [comment]
Thanks, Buck and Buck for reporting and fixing. Closing this issue for now. If there are more, please file issues and we'll fix them. Thanks.
